/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Dao.UserDao;
import Entities.User;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maynoo
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {

        initComponents();
        Design.setBackground();
        Image menuimg = Design.getMenu();
        Image titreimg = Design.getTitre();
        
        this.setTitle("Authentification");
        menuBack.setIcon(new ImageIcon(menuimg));
        titreBack.setIcon(new ImageIcon(titreimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JPanel();
        titreLabel = new javax.swing.JLabel();
        titreBack = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        mdpLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        Inscription = new javax.swing.JButton();
        menuBack = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        titre.setBackground(new java.awt.Color(255, 255, 255));
        titre.setPreferredSize(new java.awt.Dimension(1040, 97));
        titre.setLayout(null);

        titreLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titreLabel.setText("Authentification");
        titre.add(titreLabel);
        titreLabel.setBounds(16, 24, 600, 50);

        titreBack.setText("Titre Back");
        titreBack.setMaximumSize(new java.awt.Dimension(1040, 97));
        titreBack.setMinimumSize(new java.awt.Dimension(1040, 97));
        titreBack.setPreferredSize(new java.awt.Dimension(1040, 97));
        titre.add(titreBack);
        titreBack.setBounds(0, 0, 1040, 97);

        getContentPane().add(titre);
        titre.setBounds(240, 0, 1040, 97);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setMaximumSize(new java.awt.Dimension(240, 720));
        menu.setPreferredSize(new java.awt.Dimension(240, 720));
        menu.setLayout(null);

        loginLabel.setText("Login");
        loginLabel.setPreferredSize(new java.awt.Dimension(192, 36));
        menu.add(loginLabel);
        loginLabel.setBounds(24, 240, 192, 36);

        login.setMaximumSize(new java.awt.Dimension(192, 36));
        login.setMinimumSize(new java.awt.Dimension(192, 36));
        login.setPreferredSize(new java.awt.Dimension(192, 36));
        menu.add(login);
        login.setBounds(24, 280, 192, 36);

        mdpLabel.setText("Mot De Passe");
        mdpLabel.setPreferredSize(new java.awt.Dimension(192, 36));
        menu.add(mdpLabel);
        mdpLabel.setBounds(24, 320, 192, 36);

        password.setMaximumSize(new java.awt.Dimension(192, 36));
        password.setMinimumSize(new java.awt.Dimension(192, 36));
        password.setPreferredSize(new java.awt.Dimension(192, 36));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        menu.add(password);
        password.setBounds(24, 360, 192, 36);

        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(192, 36));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        menu.add(loginButton);
        loginButton.setBounds(24, 400, 192, 36);

        Inscription.setText("Inscription");
        Inscription.setPreferredSize(new java.awt.Dimension(192, 36));
        menu.add(Inscription);
        Inscription.setBounds(24, 440, 192, 36);

        menuBack.setText("Menu Back");
        menuBack.setMaximumSize(new java.awt.Dimension(240, 720));
        menuBack.setMinimumSize(new java.awt.Dimension(240, 720));
        menuBack.setPreferredSize(new java.awt.Dimension(240, 720));
        menu.add(menuBack);
        menuBack.setBounds(0, 0, 240, 720);

        getContentPane().add(menu);
        menu.setBounds(0, 0, 240, 720);

        container.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        getContentPane().add(container);
        container.setBounds(240, 97, 1040, 603);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        UserDao ud = new UserDao();
        User u = ud.RechercherParUsername(login.getText());

        if (u.getId() != 0) {
            if (u.getPassword().equals(password.getText())) {
                
                loginInfo.setUtilisateur(u);
                this.dispose();
                new AcceuilAgent().setVisible(true);
            }
        } else {

        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inscription;
    private javax.swing.JPanel container;
    private javax.swing.JTextField login;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel mdpLabel;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuBack;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel titre;
    private javax.swing.JLabel titreBack;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}
