/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Dao.DemandeDao;
import Entities.Demande;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Maynoo
 */
public class DemanderB3 extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public DemanderB3() {

        initComponents();
        Design.setBackground();
        Image titreimg = Design.getTitre();

        this.setTitle("Demander Bulletin Numero 3");
        titreLabel.setText("Demander Bulletin Numero 3");
        titreBack.setIcon(new ImageIcon(titreimg));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JPanel();
        titreLabel = new javax.swing.JLabel();
        titreBack = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        titre.setBackground(new java.awt.Color(255, 255, 255));
        titre.setPreferredSize(new java.awt.Dimension(1040, 97));
        titre.setLayout(null);

        titreLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titreLabel.setText("Authentification");
        titre.add(titreLabel);
        titreLabel.setBounds(16, 24, 600, 50);

        titreBack.setText("Titre Back");
        titreBack.setMaximumSize(new java.awt.Dimension(1040, 97));
        titreBack.setMinimumSize(new java.awt.Dimension(1040, 97));
        titreBack.setPreferredSize(new java.awt.Dimension(1040, 97));
        titre.add(titreBack);
        titreBack.setBounds(0, 0, 1040, 97);

        getContentPane().add(titre);
        titre.setBounds(240, 0, 1040, 97);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setMaximumSize(new java.awt.Dimension(240, 720));
        menu.setPreferredSize(new java.awt.Dimension(240, 720));
        menu.setLayout(null);
        getContentPane().add(menu);
        menu.setBounds(0, 0, 240, 720);
        Design.fillMenu(menu,this);

        container.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Voulez vous demander votre bulletin numero 3");

        jButton1.setText("Demander B3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jButton1)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        getContentPane().add(container);
        container.setBounds(240, 97, 1040, 603);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int n = JOptionPane.showConfirmDialog(
                    getContentPane(),
                    "Confirmer la demande pour votre bulletin numero 3?",
                    "Confirmer",
                    JOptionPane.YES_NO_OPTION);

        if (n == 0) {
            Demande d = new Demande();
            d.setType("B3");
            d.setCin(loginInfo.getUtilisateur().getCin());
            d.setEtat("En Cours");
            d.setCommentaire("");

            DemandeDao dd = new DemandeDao();
            dd.add(d);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemanderB3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemanderB3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemanderB3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemanderB3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemanderB3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel titre;
    private javax.swing.JLabel titreBack;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}
